channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - joblib=0.14.1
  - networkx=2.4
  - numpy=1.18.1
  - pandas=0.25.3
  - pymatgen=2019.12.3
  - python=3.7.0
  - rdkit=2019.09.3.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.1.3
    - tqdm==4.42.1
